config/routes.rb
Mailing::Application.routes.draw do
  # mount Mercury::Engine => '/'
  # Mercury::Engine.routes
  resources :mailing_schedules
  match "mailing_schedules/preview/:id" => "mailing_schedules#preview", :via => :get, :as => :mailing_preview

  resources :templates
  match "templates/preview/:id" => "templates#preview", :via => :get, :as => :template_preview

  resources :city_halls

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/templates/_form.html.haml
= simple_form_for(@template) do |f|
	= f.error_notification
	.form-inputs
		= f.input :name
		#wysihtml5-toolbar(style="display: none;")
			%a(data-wysihtml5-command="bold") bold
			%a(data-wysihtml5-command="insertHTML" data-wysihtml5-command-value="<blockquote>foobar</blockquote>") insert quote
			%a(data-wysihtml5-action="change_view" href="javascript:;" unselectable="on") switch to html view
		  
		= f.input :body,:input_html => {:rows => 40, :class => "wysihtml5"}
	.form-actions
		= f.button :submit
		= link_to 'Cancel', @template, :class => "button radius alert"
		= link_to 'Preview', template_preview_path(@template), target: "_blank", :class => "button radius success right" unless @template.id.blank?

:javascript
	$(document).ready(function(){
		$('.wysihtml5').wysihtml5({
			"size": 'tiny',
			"stylesheets":  ["#{stylesheet_path('mailer_responsive')}","#{stylesheet_path('mailer_responsive_media')}"], // optional, css to style the editor's content
			"font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
			"emphasis": true, //Italics, bold, etc. Default true
			"lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
			"html": true, //Button which allows you to edit the generated HTML. Default false
			"link": true, //Button to insert a link. Default true
			"image": true, //Button to insert an image. Default true,
			"color": true //Button to change color of font
		});
	})


	$(document).on('page:load', function(){
		window['rangy'].initialized = false
	})

app/views/templates/edit.html.haml
%h1 Editing template
	
= render 'form'

app/views/templates/index.html.haml
%h1 Listing Templates

%table
  %thead
    %tr
      %th Name
      %th Body
      %th Action
  %tbody
    - @templates.each do |template|
      %tr
        %td= template.name
        / %td= truncate(template.body, :length => 40)
        %td.text-center= image_tag template.snapshot(:medium)
        %td
          %ul.button-group.radius{:style => "margin-bottom: -20px"}
            %li= link_to 'Show', template, :class => "button tiny"
            %li= link_to 'Edit', edit_template_path(template), :class => "button success tiny"
            %li= link_to 'Destroy', template, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "button alert tiny"

%br

= link_to 'New Template', new_template_path, :class => "button round"

app/views/templates/new.html.haml
%h1 New template

= render 'form'

= link_to 'Back', templates_path

app/views/templates/preview.html.haml
= render 'mailer/responsive_header'
    
= @template.body.html_safe

= render 'mailer/responsive_footer'

app/views/templates/show.html.haml
%h2
	= @template.name

= image_tag @template.snapshot
%br
%br
= link_to 'Edit', edit_template_path(@template), :class => "button radius"
= link_to 'Back', templates_path, :class => "button radius alert"