config/routes.rb
Mailing::Application.routes.draw do
  # mount Mercury::Engine => '/'
  # Mercury::Engine.routes
  resources :mailing_schedules
  match "mailing_schedules/preview/:id" => "mailing_schedules#preview", :via => :get, :as => :mailing_preview

  resources :templates
  match "templates/preview/:id" => "templates#preview", :via => :get, :as => :template_preview

  resources :city_halls

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/mailing_schedule.rb
class MailingSchedule < ActiveRecord::Base
  belongs_to :template
  belongs_to :city_hall

  validates :template, presence: true
	validates :city_hall, presence: true
	validates :name, presence: true

  has_attached_file :snapshot, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :snapshot, :content_type => /\Aimage\/.*\Z/
	
end

app/controllers/mailing_schedules_controller.rb
class MailingSchedulesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_mailing_schedule, only: [:show, :edit, :update, :destroy, :preview]

  # GET /mailing_schedules
  # GET /mailing_schedules.json
  def index
    @mailing_schedules = MailingSchedule.all
  end

  # GET /mailing_schedules/1
  # GET /mailing_schedules/1.json
  def show
  end

  # GET /mailing_schedules/new
  def new
    @mailing_schedule = MailingSchedule.new
  end

  # GET /mailing_schedules/1/edit
  def edit
  end

  def preview
    render layout: false 
  end

  # POST /mailing_schedules
  # POST /mailing_schedules.json
  def create
    @mailing_schedule = MailingSchedule.new(mailing_schedule_params)

    respond_to do |format|
      if @mailing_schedule.save
        upload_image(@mailing_schedule)
        format.html { redirect_to @mailing_schedule, notice: 'Mailing schedule was successfully created.' }
        format.json { render :show, status: :created, location: @mailing_schedule }
      else
        format.html { render :new }
        format.json { render json: @mailing_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mailing_schedules/1
  # PATCH/PUT /mailing_schedules/1.json
  def update
    respond_to do |format|
      if @mailing_schedule.update(mailing_schedule_params)
        upload_image(@mailing_schedule)
        format.html { redirect_to @mailing_schedule, notice: 'Mailing schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @mailing_schedule }
      else
        format.html { render :edit }
        format.json { render json: @mailing_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailing_schedules/1
  # DELETE /mailing_schedules/1.json
  def destroy
    @mailing_schedule.destroy
    respond_to do |format|
      format.html { redirect_to mailing_schedules_url, notice: 'Mailing schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailing_schedule
      @mailing_schedule = MailingSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mailing_schedule_params
      params.require(:mailing_schedule).permit(:name, :template_id, :city_hall_id, :date, :content, :snapshot)
    end

    def upload_image(model)
      html  = render_to_string('mailing_schedules/preview' ,:layout => false)
      kit   = IMGKit.new(html)
      img   = kit.to_img(:png)
      file  = Tempfile.new(["template_#{model.id}", '.png'], 'tmp',
                         :encoding => 'ascii-8bit')
      file.write(img)
      file.flush
      model.snapshot = file
      model.save!
      file.unlink
    end
end

app/helpers/mailing_schedules_helper.rb
module MailingSchedulesHelper
end

app/views/mailing_schedules/_form.html.haml
= simple_form_for(@mailing_schedule) do |f|
  = f.error_notification
  .row
    .large-4.columns
      .form-inputs
        = f.input :name
        = f.association :template
        = f.association :city_hall
        = f.input :date, :input_html => {:class => 'small-2 large-2'}
    .large-8.columns
      .form-inputs
        = f.input :content, :input_html => {:rows => 40, :class => "wysihtml5"}

  .form-actions
    = f.button :submit
    = link_to 'Cancel', @mailing_schedule, :class => "button radius alert"

:javascript
  $(document).ready(function(){
    $('.wysihtml5').wysihtml5({
      "size": 'tiny',
      "stylesheets":  ["#{stylesheet_path('mailer_responsive')}","#{stylesheet_path('mailer_responsive_media')}"], // optional, css to style the editor's content
      "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
      "emphasis": true, //Italics, bold, etc. Default true
      "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
      "html": true, //Button which allows you to edit the generated HTML. Default false
      "link": true, //Button to insert a link. Default true
      "image": true, //Button to insert an image. Default true,
      "color": true //Button to change color of font
    });
  })


  $(document).on('page:load', function(){
    window['rangy'].initialized = false
  })

app/views/mailing_schedules/edit.html.haml
%h1 Editing mailing_schedule

= render 'form'

= link_to 'Show', @mailing_schedule
\|
= link_to 'Back', mailing_schedules_path

app/views/mailing_schedules/index.html.haml
%h1 Listing mailing_schedules

%table
  %thead
    %tr
      %th Name
      %th Template
      %th City hall
      %th Date
      %th Content
      %th Action
  %tbody
    - @mailing_schedules.each do |mailing_schedule|
      %tr
        %td= mailing_schedule.name
        %td= mailing_schedule.template.name
        %td= mailing_schedule.city_hall.name
        %td= mailing_schedule.date
        %td.text-center= image_tag mailing_schedule.snapshot(:medium)
        %td
          %ul.button-group.radius{:style => "margin-bottom: -20px"}
            %li= link_to 'Show', mailing_schedule, :class => "button tiny"
            %li= link_to 'Edit', edit_mailing_schedule_path(mailing_schedule), :class => "button success tiny"
            %li= link_to 'Destroy', mailing_schedule, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "button alert tiny"

%br

= link_to 'New Mailing schedule', new_mailing_schedule_path, :class => "button round"

app/views/mailing_schedules/new.html.haml
%h1 New mailing_schedule

= render 'form'

app/views/mailing_schedules/preview.html.haml
= render 'mailer/responsive_header'
    
= @mailing_schedule.content.html_safe

= render 'mailer/responsive_footer'

app/views/mailing_schedules/show.html.haml
%h2
  = @mailing_schedule.name
%br
%p
  %b
    Template: 
  = @mailing_schedule.template.name
%p
  %b
    City Hall: 
  = @mailing_schedule.city_hall.name
%p
  %b
    Date: 
  = @mailing_schedule.date

= image_tag @mailing_schedule.snapshot

%br
%br

= link_to 'Edit', edit_mailing_schedule_path(@mailing_schedule), :class => "button radius"
= link_to 'Back', mailing_schedules_path, :class => "button radius alert"