config/routes.rb
Mailing::Application.routes.draw do
  # mount Mercury::Engine => '/'
  # Mercury::Engine.routes
  resources :mailing_schedules
  match "mailing_schedules/preview/:id" => "mailing_schedules#preview", :via => :get, :as => :mailing_preview

  resources :templates
  match "templates/preview/:id" => "templates#preview", :via => :get, :as => :template_preview

  resources :city_halls

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/city_hall.rb
class CityHall < ActiveRecord::Base

	# Validators
	validates :city, presence: true
	validates :postalCode, presence: true
	validates :logo, :attachment_presence => true

	validates_format_of :postalCode,
                  with: /\A[0-9]{5}\z/,
                  message: "should be 12345",
                  allow_blank: true


	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/



end

app/controllers/city_halls_controller.rb
class CityHallsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_city_hall, only: [:show, :edit, :update, :destroy]

  # GET /city_halls
  # GET /city_halls.json
  def index
    @city_halls = CityHall.all
  end

  # GET /city_halls/1
  # GET /city_halls/1.json
  def show
  end

  # GET /city_halls/new
  def new
    @city_hall = CityHall.new
  end

  # GET /city_halls/1/edit
  def edit
  end

  # POST /city_halls
  # POST /city_halls.json
  def create
    @city_hall = CityHall.new(city_hall_params)

    respond_to do |format|
      if @city_hall.save
        format.html { redirect_to @city_hall, notice: 'City hall was successfully created.' }
        format.json { render :show, status: :created, location: @city_hall }
      else
        format.html { render :new }
        format.json { render json: @city_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /city_halls/1
  # PATCH/PUT /city_halls/1.json
  def update
    respond_to do |format|
      if @city_hall.update(city_hall_params)
        format.html { redirect_to @city_hall, notice: 'City hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @city_hall }
      else
        format.html { render :edit }
        format.json { render json: @city_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_halls/1
  # DELETE /city_halls/1.json
  def destroy
    @city_hall.destroy
    respond_to do |format|
      format.html { redirect_to city_halls_url, notice: 'City hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city_hall
      @city_hall = CityHall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_hall_params
      params.require(:city_hall).permit(:name, :city, :postalCode, :logo)
    end
end

app/helpers/city_halls_helper.rb
module CityHallsHelper
end

app/views/city_halls/_form.html.haml
= simple_form_for(@city_hall) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :city
    = f.input :postalCode
    = f.file_field :logo

  .form-actions
    = f.button :submit
    = link_to 'Cancel', @city_hall, :class => "button radius alert"

app/views/city_halls/edit.html.haml
%h1= "Editing City Hall : " + @city_hall.city

= render 'form'

app/views/city_halls/index.html.haml
%h1 Listing City Halls

%table
  %thead
    %tr
      %th Name
      %th City
      %th Postalcode
      %th Logo
      %th Action
  %tbody
    - @city_halls.each do |city_hall|
      %tr
        %td= city_hall.name
        %td= city_hall.city
        %td= city_hall.postalCode
        %td= image_tag city_hall.logo.url(:thumb)
        %td
          %ul.button-group.radius{:style => "margin-bottom: -20px"}
            %li= link_to 'Show', city_hall, :class => "button tiny"
            %li= link_to 'Edit', edit_city_hall_path(city_hall), :class => "button tiny success"
            %li= link_to 'Destroy', city_hall, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "button alert tiny"

%br

= link_to 'New City hall', new_city_hall_path, :class => "button round"

app/views/city_halls/new.html.haml
%h1 New city_hall

= render 'form'

= link_to 'Back', city_halls_path

app/views/city_halls/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @city_hall.name
%p
  %b City:
  = @city_hall.city
%p
  %b Postalcode:
  = @city_hall.postalCode

= link_to 'Edit', edit_city_hall_path(@city_hall), :class => "button radius"
= link_to 'Back', city_halls_path, :class => "button radius alert"