config/routes.rb
Mailing::Application.routes.draw do
  # mount Mercury::Engine => '/'
  # Mercury::Engine.routes
  resources :mailing_schedules
  match "mailing_schedules/preview/:id" => "mailing_schedules#preview", :via => :get, :as => :mailing_preview

  resources :templates
  match "templates/preview/:id" => "templates#preview", :via => :get, :as => :template_preview

  resources :city_halls

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Mailing', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul.left
      = render 'layouts/navigation_links_left'
    %ul.right
      = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links_left.html.haml
- if user_signed_in?
	%li= link_to 'City Halls', city_halls_path
	%li= link_to 'Templates', templates_path
	%li= link_to 'Mailing Schedules', mailing_schedules_path
	%li= link_to 'Users', users_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
	%li.has-dropdown
		=link_to "#" do
			%i.fi-torso
			=current_user.name
		%ul.dropdown
			%li
				=link_to edit_user_registration_path do
					%i.fi-widget
					='Edit account'
			%li
				=link_to destroy_user_session_path, :method=>'delete' do
					%i.fi-eject
					= 'Logout'
- else
	%li
		= link_to new_user_session_path do
			%i.fi-torso
			= 'Login'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Mailing'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Mailing'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag params[:controller]
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .row
        .small-12.large-12.columns.large-centered
          = render 'layouts/messages'
          = yield
    %footer
      .row
        .small-12.larger-12.columns
          © Benjamin Desmarez 2014 - All rights reserved.
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.